version: '2'
services:
  mysql:
    image: docker.io/bitnami/mysql:8
    ports:
      - '9918:3306'
    volumes:
      - '~/docker.mounts.d/mysql:/bitnami/mysql'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=bn_ghost
      - MYSQL_DATABASE=bitnami_ghost
  ghost:
    image: ghcr.io/sid0831/ghost-container:latest
    ports:
      - '8080:2368'
    volumes:
      - '~/docker.mounts.d/ghost:/bitnami/ghost'
    depends_on:
      - mysql
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - GHOST_DATABASE_HOST=mysql
      - GHOST_DATABASE_PORT_NUMBER=3306
      - GHOST_DATABASE_USER=bn_ghost
      - GHOST_DATABASE_NAME=bitnami_ghost
      - BITNAMI_DEBUG=true
